export { default as Login } from "./Login/Login";
export { default as CreateAccountP } from "./CreateAccountP/CreateAccountP";
export { default as ForgotPassword } from "./ForgetPassword/ForgotPassword";
export { default as CreateAccountH } from "./CreateAccountH/CreateAccountH";
export { default as Org_Des } from "./CreateAccountH/Org_Des";
export { default as CreatePass } from "./CreateAccountH/CreatePass";
export { default as CreatePassP } from "./CreateAccountP/CreatePassP";
export { default as Home } from "./Home/Home";
export { store } from "./store/store";
export { default as Otp } from "./ForgetPassword/Otp";
